version: '3.4'

services:
  identifier:
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    ports:
      - "8899:80"
  database:
    ports:
      - "8890:8890"
  friends:
    environment:
      NODE_ENV: "development"
    ports:
      - 9229:9229
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - database:database
    volumes:
      - ./config/migrations:/data/migrations