version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resourcecache:resource
      - books:books
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/sparql-parser:0.0.1
    volumes:
      - ./config/authorization:/config
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  books:
    image: madnificent/books-service:2.0.0
    links:
      - database:database
  friends:
    image: semtech/mu-javascript-template:1.8.0
    links:
      - database:database
  resource:
    image: semtech/mu-cl-resources:1.23.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://resourcecache/.mu/clear-keys"
  file:
    image: semtech/mu-file-service:3.4.0
    links:
      - database:database
    volumes:
      - ./data/files:/share
  login:
    image: semtech/mu-login-service:3.0.0
    links:
      - database:database
  registration:
    image: semtech/mu-registration-service:2.7.3
    links:
      - database:database
  deltanotifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config
  resourcecache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
  search:
    image: semtech/mu-search:0.9.0
    links:
      - database:database
    volumes:
      - ./config/search:/config
  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.0.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node